# Generated by Django 3.1.3 on 2020-12-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authoricon',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='authorname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
