"""
Django settings for c3LocalSNS_Backend project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from .base import *

import os

ALLOWED_HOSTS = ['*']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.setdefault('DB_NAME', 'c3'),
        'USER': os.environ.setdefault('DB_USER', 'c3'),
        'PASSWORD': os.environ.setdefault('DB_PASSWORD', 'c3'),
        'HOST': os.environ.setdefault('DB_HOST', 'db'),
        'PORT': os.environ.setdefault('DB_PORT', '5432')
    }
}

NOTIFICATION = {
    'REDIS': {
        'REDIS_HOST': os.environ.setdefault('REDIS_HOST', 'redis'),
        'REDIS_PORT': os.environ.setdefault('REDIS_PORT', '6379')
    }
}
