"""
Django settings for c3LocalSNS_Backend project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from .base import *

import os

import environ

env = environ.Env(
    DEBUG = (bool, False)
)

ALLOWED_HOSTS = ['*']

DEBUG = env('DEBUG')

SECRET_KEY = env('SECRET_KEY')

DATABASES = {
    'default': env.db()
}

NOTIFICATION = {
    'REDIS': {
        'REDIS_URL': os.environ.setdefault('REDIS_URL', 'redis://redis:6379')
    }
}
